apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    mongo: express
spec:
  replicas: 1
  selector:
    matchLabels:
      mongo: express
  template:
    metadata:
      labels:
        mongo: express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express:latest
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config-map
                  key: database_url
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb_username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb_password

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  type: LoadBalancer
  selector:
    mongo: express
  ports:
    - targetPort: 8081
      port: 8081
      nodePort: 30049