apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb_username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb_password

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    env: dev
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP